--- DATA EXPLORATION ---

--- DATA
USE Portfolio_Project;
SELECT TOP 5 * FROM Sales_Data_Case

--- CHECKING UNIQUE VALUES
SELECT DISTINCT status FROM Sales_Data_Case --- CORRECT

SELECT DISTINCT YEAR_ID FROM Sales_Data_Case --- 
SELECT DISTINCT MONTH_ID FROM Sales_Data_Case  
WHERE YEAR_ID = 2005 --- INCOMPLETE YEAR

SELECT DISTINCT PRODUCTLINE FROM Sales_Data_Case --- CORRECT

SELECT DISTINCT COUNTRY FROM Sales_Data_Case --- CORRECT
ORDER BY COUNTRY

SELECT DISTINCT DEALSIZE FROM Sales_Data_Case --- CORRECT

SELECT DISTINCT TERRITORY FROM Sales_Data_Case --- CORRECT

--- DATA ANALYSIS ---

--- SALES BY PRODUCTLINE
SELECT PRODUCTLINE, SUM(SALES) AS TOTALSALES 
FROM Sales_Data_Case
GROUP BY PRODUCTLINE
ORDER BY 2 DESC

--- SALES BY YEAR
SELECT YEAR_ID, SUM(SALES) AS TOTALSALES 
FROM Sales_Data_Case
GROUP BY YEAR_ID
ORDER BY 2 DESC

--- SALES BY DEALSIZE
SELECT DEALSIZE, SUM(SALES) AS TOTALSALES 
FROM Sales_Data_Case
GROUP BY DEALSIZE
ORDER BY 2 DESC

--- BEST MONTH FOR SALES IN SPECIFIC YEAR
SELECT MONTH_ID, SUM(SALES) AS TOTALSALES, COUNT(ORDERNUMBER) AS TOTALORDER
FROM Sales_Data_Case
WHERE YEAR_ID = 2004 --- CHANGE YEAR
GROUP BY MONTH_ID
ORDER BY 2 DESC

	--- NOVEMBER HAS HIGHEST SALES, WHAT PRODUCT DO THEY SELL
	SELECT MONTH_ID, PRODUCTLINE, SUM(SALES) AS TOTALSALES, COUNT(ORDERNUMBER) AS TOTALORDER
	FROM Sales_Data_Case
	WHERE YEAR_ID = 2003 AND month_id = 11 --- CHANGE YEAR
	GROUP BY MONTH_ID, PRODUCTLINE
	ORDER BY 3 DESC

--- BEST CONSUMER (METHOD RFM - RECENCY, FREQUENCY, MONETARY)
DROP TABLE IF EXISTS #RFM;

WITH RFM AS
(
	SELECT CUSTOMERNAME, 
		SUM(SALES) AS MONETARYVALUE, 
		AVG(SALES) AS AVGMONETARYVALUE, 
		COUNT(ORDERNUMBER) AS FREQUENCY,
		MAX(ORDERDATE) AS LASTORDERDATE,
		(SELECT MAX(ORDERDATE) FROM Sales_Data_Case) AS MAXORDERDATE,
		DATEDIFF(DD,MAX(ORDERDATE), (SELECT MAX(ORDERDATE) FROM Sales_Data_Case)) AS RECENCY
	FROM Sales_Data_Case
	GROUP BY CUSTOMERNAME
),
RFM_CALC AS
(
	SELECT R.*,
		NTILE(4) OVER (ORDER BY RECENCY DESC) AS RFM_RECENCY,
		NTILE(4) OVER (ORDER BY FREQUENCY) AS RFM_FREQUENCY,
		NTILE(4) OVER (ORDER BY MONETARYVALUE) AS RFM_MONETARYVALUE
	FROM RFM R
)
SELECT C.*, RFM_RECENCY + RFM_FREQUENCY + RFM_MONETARYVALUE AS RFM_CELL,
	CAST(RFM_RECENCY AS VARCHAR) + CAST(RFM_FREQUENCY AS VARCHAR) + CAST(RFM_MONETARYVALUE AS VARCHAR) AS RFM_STRING
	INTO #RFM
FROM RFM_CALC C

--- 
SELECT CUSTOMERNAME, RFM_RECENCY, RFM_FREQUENCY, RFM_MONETARYVALUE,
	CASE 
		WHEN RFM_STRING in (111, 112, 114, 121, 122, 123, 132, 133, 134, 211, 212, 144, 141) THEN 'LOST CUSTOMERS'  
		WHEN RFM_STRING in (311, 411, 412, 331) THEN 'NEW CUSTOMER'
		WHEN RFM_STRING in (221, 222, 223, 232, 233, 243, 244, 322) THEN 'POTENCIAL CHURNERS'
		WHEN RFM_STRING in (323, 333,321, 421, 422, 423, 332, 334, 342, 343, 344, 432) THEN 'ACTIVE' 
		WHEN RFM_STRING in (433, 434, 443, 444) THEN 'LOYAL'
	END AS RFM_SEGMENT
FROM #RFM

--- PRODUCTS MOST SOLD TOGETHER
SELECT DISTINCT OrderNumber, STUFF
	(
		(SELECT ',' + PRODUCTCODE
		FROM Sales_Data_Case AS P
		WHERE ORDERNUMBER IN 
			(

				SELECT ORDERNUMBER
				FROM (
					SELECT ORDERNUMBER, COUNT(*) AS RN
					FROM Sales_Data_Case
					WHERE status = 'Shipped'
					GROUP BY ORDERNUMBER
				) AS M
				WHERE RN = 3
			)
			AND P.ORDERNUMBER = S.ORDERNUMBER
			FOR XML PATH (''))

			, 1, 1, '') ProductCodes

FROM Sales_Data_Case S
ORDER BY 2 DESC

--- HIGHEST SALES PER COUNTRY
SELECT COUNTRY, SUM(SALES) 
FROM Sales_Data_Case
GROUP BY COUNTRY
ORDER BY 2 DESC

--- PRODUCT HIGHEST IN UNITED STATES
SELECT PRODUCTLINE, SUM(SALES) AS TOTALSALES
FROM Sales_Data_Case
WHERE country = 'USA'
GROUP BY PRODUCTLINE
ORDER BY 2 DESC
